version: "3.7"


volumes:
  mysql-data:
    external: true

services:
  mysqldb:
    image: mysql:8.0.32-debian
    container_name: mysqldb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: "testuser"
      MYSQL_PASSWORD: "testpassword"
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "my_data"
  
  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
    links:
      - "mysqldb:db"
    depends_on:
      - mysqldb
