version: "3.7"


volumes:
  mysql-data:
    external: true

services:
  mysqldb:
    image: mysql:8.0.32-debian
    container_name: mysqldb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "my_data"

  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - "8082:80"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    links:
      - "mysqldb:db"
    depends_on:
      - mysqldb

  myjavaapp:
    image: 164.90.234.134:5003/repository/my-docker-repo/myapp:1.0.0
    ports:
      - "8080:8080"
    environment:
      DB_NAME: "my_data"
      DB_USER: "${MYSQL_USER}"
      DB_PWD: "${MYSQL_PASSWORD}"
      DB_SERVER: "mysqldb"
    depends_on:
      - mysqldb
